-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Tempo de geração: 28-Jul-2022 às 19:34
-- Versão do servidor: 8.0.29
-- versão do PHP: 8.1.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `conteudo`
--

-- --------------------------------------------------------

--
-- Estrutura da tabela `pagina`
--

CREATE TABLE `pagina` (
  `id` int NOT NULL,
  `titulo` varchar(40) NOT NULL,
  `sinopse1` varchar(10000) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `estrelas` int NOT NULL,
  `lancamento` date NOT NULL,
  `episodios` int NOT NULL,
  `tipo` varchar(10) NOT NULL,
  `genero` varchar(50) NOT NULL,
  `studio` varchar(40) NOT NULL,
  `criador` varchar(25) NOT NULL,
  `foto` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8  COLLATE=utf8_general_ci;

--
-- Extraindo dados da tabela `pagina`
--

INSERT INTO `pagina` (`id`, `titulo`, `sinopse1`, `estrelas`, `lancamento`, `episodios`, `tipo`, `genero`, `studio`, `criador`, `foto`) VALUES
(1, 'Adachi to Shimamura', 'Em algum lugar da escola ao meio-dia, pode-se ouvir o som de duas meninas jogando tênis de mesa juntas enquanto esperam o tempo passar. Como por destino, duas alunas - Sakura Adachi e Hougetsu Shimamura - tropeçam uma na outra no segundo andar do ginásio da escola. À medida que gradualmente promovem uma amizade nascente, seus sentimentos uma pela outra só se tornam mais ambíguos. Aproximando-se a cada dia, as duas devem aprender a navegar em suas personalidades contrastantes, bem como determinar a profundidade de sua afeição uma pela outra.\r\n\r\nA natureza desse relacionamento muda gradualmente quando uma delas começa a desenvolver sentimentos além dos limites de um relacionamento platônico. Mesmo assim, Adachi e Shimamura devem perceber se formar um vínculo mais forte do que a amizade os aproximará ou os separará.', 5, '2020-10-09', 12, 'TV', 'Yuri, Romance, Slice of Life', 'Tezuka Productions', 'Hitoma Iruma', 'adachitoshimamura'),
(2, 'Asagao to Kase-san', 'Yui Yamada, uma colegial apaixonada por plantas e jardinagem, começa a namorar Tomoka Kase, a craque do time de atletismo de sua escola. Yui é tímida, feminina e nunca esteve em um relacionamento. Por outro lado, Tomoka é vivaz, moleca e popular entre seus amigos. Apesar de serem diferentes em tantos aspectos, elas tentam entender e apoiar uma a outra enquanto experimentam a onda de alegria que acompanha a magia do primeiro amor.\r\n\r\n\r\nAsagao to Kase-san é um conto emocionante de duas garotas lidando com seus sentimentos cada vez maiores uma pela outra, juntamente com outras preocupações que atormentam os corações das donzelas apaixonadas.', 3, '2018-07-09', 1, 'TV', 'Romance, Yuri', 'Zexcs', 'Hiromi Takashima', 'asagaotokasesan'),
(3, 'Attack on Titan', 'Séculos atrás, a humanidade foi massacrada até quase a extinção por monstruosas criaturas humanóides chamadas Titãs, forçando os humanos a se esconderem com medo atrás de enormes paredes concêntricas. O que torna esses gigantes realmente aterrorizantes é que seu gosto pela carne humana não nasce da fome, mas do que parece ser do prazer. Para garantir sua sobrevivência, os remanescentes da humanidade começaram a viver dentro de barreiras defensivas, resultando em cem anos sem um único encontro de titãs.\r\n\r\nNo entanto, essa calma frágil logo é quebrada quando um titã colossal consegue romper a parede externa supostamente inexpugnável, reacendendo a luta pela sobrevivência contra as abominações devoradoras de homens.  Depois de testemunhar uma terrível perda pessoal nas mãos das criaturas invasoras, Eren Yeager dedica sua vida à sua erradicação, alistando-se no Survey Corps, uma unidade militar de elite que combate os impiedosos humanóides fora da proteção das muralhas.\r\n\r\nEren, sua irmã adotiva Mikasa Ackerman e seu amigo de infância Armin Arlert se juntam à guerra brutal contra os Titãs e correm para descobrir uma maneira de derrotá-los antes que as últimas paredes sejam ', 4, '2013-04-07', 25, 'TV', 'Ação, Drama', 'Wit Studio', 'Hajime Isayama', 'attackontitan'),
(6, 'Bloom Into You', 'Yuu Koito sempre foi fascinado por mangás shoujo românticos e letras de canções de amor. Ela espera pacientemente que as asas do amor brotem e façam seu coração palpitar no dia em que finalmente recebe uma confissão. No entanto, quando seu colega de classe do ensino médio declara seu amor por ela durante a formatura, ela se sente inesperadamente vazia. A percepção a atinge: ela entende o romance como um conceito, mas é incapaz de experimentar o sentimento em primeira mão.\r\n\r\nAgora, tendo se matriculado no ensino médio, Yuu, desconcertada e desanimada, ainda está ruminando sobre como responder ao seu pretendente. Lá, ela encontra a aparentemente impecável presidente do conselho estudantil, Touko Nanami, rejeitando com maturidade uma confissão própria. Agitado pela maneira elegante de Touko, Yuu se aproxima dela pedindo conselhos, apenas para ficar perplexa quando a presidente se confessa para ela! Yuu rapidamente se encontra na palma da mão de Touko e, sem saber, se coloca em um caminho para encontrar a emoção que há muito a iludiu.', 5, '2018-10-05', 13, 'TV', 'Drama, Romance, Yuri', 'TROYCA', 'Nio Nakatani', 'bloomintoyou'),
(7, 'Hinamatsuri', 'Enquanto se diverte com a conquista bem-sucedida de um vaso premiado para sua coleção, Yoshifumi Nitta, um membro da yakuza, é rudemente interrompido quando uma cápsula grande e peculiar de repente se materializa e cai em sua cabeça. Ele abre a cápsula para revelar uma jovem de cabelos azuis, que não divulga nada sobre si mesma além de seu nome - Hina - e o fato de possuir imensos poderes. \r\n\r\nComo se as coisas não pudessem piorar, ela perde o controle e desencadeia uma explosão se seus poderes não forem usados. Sem outra escolha, Nitta se torna seu cuidador. Para deixá-la usar seus poderes livremente, Nitta pede a Hina para ajudar com um acordo de construção, que corre bem. Mas enquanto isso está acontecendo, um grupo yakuza rival ataca secretamente seu chefe. <br><br> Para o choque de Nitta, seus colegas depois colocam a culpa nele! Encarregado de atacar o grupo rival em retaliação, Nitta se fortalece e chega ao esconderijo deles. Mas, de repente, Hina entra inesperadamente e o ajuda a acabar com todo o grupo. Acontece que Hina pode se tornar um ativo valioso para Nitta e seu negócio yakuza, desde que ela não use seus poderes nele primeiro! E assim começa a estranha vida desta dupla inusitada.', 4, '2018-04-06', 12, 'TV', 'Comédia, Sobrenatural', 'Feel.', 'Masao Ohtake', 'hinamatsuri'),
(8, 'Koe no Katachi', 'Como um jovem selvagem, o estudante do ensino fundamental Shouya Ishida procurou vencer o tédio das maneiras mais cruéis. Quando a surda Shouko Nishimiya se transfere para sua classe, Shouya e o resto de sua classe a intimidam sem pensar por diversão. No entanto, quando sua mãe notifica a escola, ele é apontado e culpado por tudo que foi feito a ela. Com Shouko sendo transferido da escola, Shouya fica à mercê de seus colegas de classe. Ele é impiedosamente ostracizado durante todo o ensino fundamental e médio, enquanto os professores fecham os olhos.\r\n\r\nAgora em seu terceiro ano do ensino médio, Shouya ainda é atormentado por seus erros quando jovem. Lamentando sinceramente suas ações passadas, ele parte em uma jornada de redenção: encontrar Shouko mais uma vez e fazer as pazes. Koe no Katachi conta a comovente história do reencontro de Shouya com Shouko e suas tentativas honestas de se redimir, enquanto é continuamente assombrado pelas sombras de seu passado.', 5, '2017-09-17', 1, 'Filme', 'Drama', 'Kyoto Animation', 'Yoshitoki Ōima', 'koenokatachi'),
(9, 'Lycoris Recoil', 'Se há paz no mundo, é graças à Lycoris, uma organização secreta de combate ao crime composta apenas por garotas. Suas agentes mais poderosas são a despreocupada Chisato e a talentosa e misteriosa Takina. Juntas, elas trabalham em um café, servindo bebidas e doces, cuidando de bebês, fazendo compras e ensinando japonês.', 4, '2022-07-02', 13, 'TV', 'Ação', 'A-1 Pictures', 'Shingo Adachi', 'lycorisrecoil'),
(10, 'Naruto Shippuden', 'Já se passaram dois anos e meio desde que Naruto Uzumaki deixou Konohagakure, a Vila Oculta da Folha, para treinamento intenso após eventos que alimentaram seu desejo de ser mais forte. Agora a Akatsuki, a misteriosa organização de ninjas desonestos de elite, está se aproximando de seu grande plano que pode ameaçar a segurança de todo o mundo shinobi.\r\n\r\nEmbora Naruto seja mais velho e eventos sinistros surjam no horizonte, ele mudou pouco em personalidade - ainda indisciplinado e infantil - embora agora esteja muito mais confiante e possua uma determinação ainda maior para proteger seus amigos e sua casa. Aconteça o que acontecer, Naruto seguirá lutando pelo que é importante para ele, mesmo às custas de seu próprio corpo, na continuação da saga sobre o menino que deseja se tornar Hokage.', 3, '2007-02-15', 500, 'TV', 'Ação, Aventura, Fantasia', 'Pierrot', 'Masashi Kishimoto', 'narutoshippuden'),
(11, 'One Piece', 'Gol D. Roger era conhecido como o \"Rei dos Piratas\", o ser mais forte e mais infame que navegou na Grand Line. A captura e execução de Roger pelo Governo Mundial trouxe uma mudança em todo o mundo. Suas últimas palavras antes de sua morte revelaram a existência do maior tesouro do mundo, One Piece. Foi essa revelação que trouxe a Grande Era dos Piratas, homens que sonhavam em encontrar One Piece - que promete uma quantidade ilimitada de riqueza e fama - e possivelmente o auge da glória e o título de Rei dos Piratas.\r\n\r\nEntra Monkey D. Luffy, um garoto de 17 anos que desafia sua definição padrão de pirata. Em vez da persona popular de um pirata perverso, endurecido e desdentado saqueando aldeias por diversão, a razão de Luffy ser um pirata é pura maravilha: o pensamento de uma aventura emocionante que o leva a pessoas intrigantes e, finalmente, ao tesouro prometido. Seguindo os passos de seu herói de infância, Luffy e sua equipe viajam pela Grand Line, vivenciando aventuras loucas, desvendando mistérios sombrios e lutando contra inimigos fortes, tudo para alcançar a mais cobiçada de todas as fortunas – One Piece.', 4, '1999-10-20', 1027, 'TV', 'Ação, Aventura, Fantasia', 'Toei Animation', 'Eiichiro Oda', 'onepiece'),
(12, 'Spy x Familly', 'Políticos corruptos, nacionalistas frenéticos e outras forças belicistas colocam constantemente em risco o fino verniz de paz entre os países vizinhos Ostania e Westalis. Apesar de suas tramas, o renomado espião e mestre do disfarce \"Crepúsculo\" cumpre missões perigosas uma após a outra na esperança de que nenhuma criança tenha que experimentar os horrores da guerra. <br><br>Na movimentada cidade ostaniana de Berlint, Twilight veste o pseudônimo de \"Loid Forger\", um estimado psiquiatra. No entanto, sua verdadeira intenção é reunir informações sobre o proeminente político Donovan Desmond, que raramente aparece em público na escola de seus filhos: a prestigiosa Eden Academy. Recrutando a ajuda do funcionário solteiro da prefeitura Yor Briar para agir como sua esposa e adotando a curiosa órfã de seis anos Anya como sua filha, Loid põe em prática seu plano mestre. Ele matriculará Anya na Eden Academy, onde Loid espera que ela se destaque e lhe dê a oportunidade de conhecer Donovan sem levantar suspeitas.\r\n\r\nInfelizmente para Loid, mesmo um homem com seus talentos tem dificuldade em representar a figura de um pai e marido amoroso. E assim como Loid está escondendo sua verdadeira identidade, Yor - que é um assassino subterrâneo conhecido como \"Princesa do Espinho\" - e Anya - uma esper que pode ler a mente das pessoas - também não têm planos de divulgar seus próprios segredos. Embora esta família perfeita seja baseada na decepção, os Forgers gradualmente entendem que o amor que compartilham um pelo outro supera tudo.', 5, '2022-04-09', 12, 'TV', 'Ação, Comédia', 'Wit Studio, CloverWorks', 'Tatsuya Endo', 'spyxfamilly'),
(13, 'Tenki No Ko', 'Atualmente, Tóquio está enfrentando pancadas de chuva que parecem interromper o ritmo habitual de todos que vivem lá. Em meio a essa chuva aparentemente eterna, chega o estudante fugitivo do ensino médio Hodaka Morishima, que luta para se sustentar financeiramente – acabando com um emprego em uma pequena editora. Ao mesmo tempo, a órfã Hina Amano também se esforça para encontrar trabalho para sustentar a si mesma e a seu irmão mais novo. Ambos os destinos se entrelaçam quando Hodaka tenta resgatar Hina de homens obscuros, decidindo fugir juntos.\r\n\r\nPosteriormente, Hodaka descobre que Hina tem um poder estranho, mas surpreendente: a capacidade de chamar o sol sempre que ela reza por ele. Com o clima incomum de Tóquio em mente, Hodaka vê o potencial dessa habilidade. Ele sugere que Hina deve se tornar uma \"garota do sol\" - alguém que vai limpar o céu para as pessoas quando elas mais precisam. As coisas começam a melhorar para eles no início. No entanto, é do conhecimento comum que o poder sempre vem com um preço alto...', 4, '2019-07-19', 1, 'Filme', 'Drama, Romance, Fantasia, Slice of Life', 'CoMix Wave Films', 'Makoto Shinkai', 'tenkinoko'),
(14, 'Tsuki ga Kirei', 'Com o Clube de Voluntariado já consolidado, vem recebendo mais solicitações de alunos em busca de soluções para seus diversos problemas. No entanto, os membros do clube muitas vezes lutam para concordar quando se trata de seus ideais de resolução de problemas.\r\n\r\nAs sugestões que Hachiman Hikigaya recomenda frequentemente colidem com as de Yukino Yukinoshita, fraturando as relações dentro do clube. Apesar de suas diferenças, com o trio constantemente tentando encontrar um terreno comum, eles podem em breve chegar a um ponto em que descubram algo genuíno.', 4, '2017-04-07', 1, 'Filme', 'Romance', 'feel.', 'Yūko Kakihara', 'tsukigakirei'),
(15, 'OreGairu', 'Com o Clube de Voluntariado já consolidado, vem recebendo mais solicitações de alunos em busca de soluções para seus diversos problemas. No entanto, os membros do clube muitas vezes lutam para concordar quando se trata de seus ideais de resolução de problemas.\r\n\r\nAs sugestões que Hachiman Hikigaya recomenda frequentemente colidem com as de Yukino Yukinoshita, fraturando as relações dentro do clube. Apesar de suas diferenças, com o trio constantemente tentando encontrar um terreno comum, eles podem em breve chegar a um ponto em que descubram algo genuíno.', 4, '2015-04-03', 13, 'TV', 'Comédia, Romance', 'feel.', 'Wataru Watari', 'oregairu'),
(20, 'One Punch Man', 'O aparentemente inexpressivo Saitama tem um hobby bastante único: ser um herói. A fim de perseguir seu sonho de infância, Saitama treinou incansavelmente por três anos, perdendo todo o cabelo no processo. Agora, Saitama é tão poderoso que pode derrotar qualquer inimigo com apenas um soco. No entanto, não ter ninguém capaz de igualar sua força levou Saitama a um problema inesperado - ele não é mais capaz de aproveitar a emoção de lutar e ficou bastante entediado.\r\n\r\nUm dia, Saitama chama a atenção do ciborgue Genos, de 19 anos, que testemunha seu poder e deseja se tornar discípulo de Saitama. Genos propõe que os dois se juntem à Hero Association para se tornarem heróis certificados que serão reconhecidos por suas contribuições positivas para a sociedade. Saitama, que está chocado que ninguém sabe quem ele é, rapidamente concorda. Conhecendo novos aliados e enfrentando novos inimigos, Saitama embarca em uma nova jornada como membro da Hero Association para experimentar a emoção da batalha que ele sentiu uma vez.', 4, '2015-10-05', 12, 'TV', 'Ação, Comédia', 'Madhouse', 'One e Yusuke Murata', 'onepunchman'),
(44, 'Yuru Yuri', 'As meninas do Amusement Club retornam em Yuru Yuri♪♪, encontrando novas maneiras de tornar a passagem do tempo ainda mais agradável. Seus membros consistem no sempre enérgico Kyouko Toshinou; calma e sensata Yui Funami; educado, mas muitas vezes esquecido Akari Akaza; e Chinatsu Yoshikawa, que tropeçou nos outros enquanto procurava o Clube da Cerimônia do Chá. Juntos, eles são o Clube de Diversões, que tem a tarefa enganosamente simples de manter seus membros entretidos.\r\n\r\nJunto com o Conselho Estudantil e o estranho membro da família, eles se esforçam para aproveitar ao máximo sua juventude. Seja uma viagem a uma fonte termal ou terminando a lição de casa atrasada, suas vidas nunca são monótonas e sempre encontrarão uma desculpa para passar o tempo juntos.', 4, '2012-09-03', 12, 'TV', 'Comédia, Yuri', 'Doga Kobo', 'Namori', 'yuruyuri'),
(45, 'School Days', 'O estudante do ensino médio Makoto Itou percebe Kotonoha Katsura pela primeira vez no início de seu segundo semestre, primeiro ano. Imediatamente, ele fica encantado com sua beleza, mas sua timidez não permite que ele se aproxime dela, mesmo que eles andem no mesmo trem todos os dias. Em vez disso, ele tira uma foto dela em segredo e a define como papel de parede de seu celular: um amuleto que, se mantido em segredo, supostamente ajudaria você a perceber seu amor. No entanto, o colega de classe Sekai Saionji vê a foto, mas em vez de denunciá-lo, ela se oferece para ajudar a colocá-lo com Kotonoha - chegando a fazer amizade com ela apenas para ele. Assim, o trio começa uma amizade bastante improvisada.\r\n\r\nSchool Days segue a vida desses três adolescentes enquanto eles atravessam as alegrias e dificuldades que acompanham o ensino médio. Em uma história viva e repleta de romance e melancolia, a história desses três alunos permanecerá na memória por muito tempo após a importante conclusão.\r\n\r\n', 1, '2007-07-04', 12, 'TV', 'Dama, Romance', 'TNK', 'Homare Sakazuki', 'schooldays'),
(46, 'Toubun no Hanayome', 'Através da orientação diligente de seu tutor Fuutarou Uesugi, o desempenho acadêmico dos quíntuplos Nakano mostra sinais de melhora, mesmo que seu caminho para a formatura ainda seja difícil. No entanto, como eles continuam a causar várias situações que atrasam qualquer tutoria real, Fuutarou torna-se cada vez mais envolvido com suas vidas pessoais, complicando ainda mais seu relacionamento um com o outro.\r\n\r\nEm outra nota, Fuutarou lentamente começa a perceber a existência de uma possível conexão entre ele e o passado que ele acredita ter compartilhado com uma das cinco garotas. Com os sentimentos de todos começando a se desenvolver e se sobrepor, eles serão capazes de manter seu vínculo estritamente com o de um professor e seus alunos – ou será algo completamente diferente?\r\n', 2, '2021-01-08', 12, 'TV', 'Comédia, Romance', 'Bibury Animation Studios', 'Negi Haruba', 'toubunnohanayome'),
(48, 'Kaguya-sama wa Kokurasetai', 'Depois de umas férias de verão lentas, mas agitadas, o segundo mandato da Academia Shuchiin está começando com força total. Com a transição de agosto para setembro, o aniversário de Miyuki Shirogane se aproxima cada vez mais, deixando Kaguya Shinomiya em uma situação séria sobre como celebrá-lo. Além disso, o mandato do 67º conselho estudantil da escola está chegando ao fim. \r\n\r\nDevido aos membros do conselho estarem em classes diferentes, a única vez que Kaguya e Miyuki têm que ficar juntos logo desaparecerá, colocando todos os seus planos em risco. Uma longa e difícil eleição que decidirá o destino do novo conselho estudantil aguarda, enquanto vários desafiantes lutam pelo cobiçado título de presidente.', 4, '2020-04-11', 12, 'TV', 'Comédia', 'A-1 Pictures', 'Aka Akasaka', 'kaguyasamawakokurasetai'),
(49, 'Hunter x Hunter', 'Os caçadores se dedicam a realizar tarefas perigosas, desde atravessar territórios inexplorados do mundo até localizar itens e monstros raros. Antes de se tornar um Hunter, é preciso passar no Exame Hunter - um processo de seleção de alto risco no qual a maioria dos candidatos acaba deficiente ou pior, falecido. Participantes ambiciosos que desafiam o notório exame carregam sua própria razão. O que impulsiona Gon Freecss, de 12 anos, é encontrar Ging, seu pai e um caçador. Acreditando que conhecerá seu pai se tornando um caçador, Gon dá o primeiro passo para trilhar o mesmo caminho.\r\n\r\nDurante o Exame Hunter, Gon faz amizade com o estudante de medicina Leorio Paladiknight, o vingativo Kurapika e o ex-assassino Killua Zoldyck. Embora seus motivos sejam muito diferentes um do outro, eles se unem por um objetivo comum e começam a se aventurar em um mundo perigoso.', 5, '2011-10-02', 148, 'TV', 'Ação, Aventura, Fantasia', 'Madhouse', 'Yoshihiro Togashi', 'hunterxhunter'),
(50, 'Your Name', 'Mitsuha Miyamizu, uma colegial, deseja viver a vida de um menino na movimentada cidade de Tóquio - um sonho que contrasta com sua vida atual no campo. Enquanto isso, na cidade, Taki Tachibana vive uma vida ocupada como estudante do ensino médio, enquanto faz malabarismos com seu trabalho de meio período e espera um futuro na arquitetura. Um dia, Mitsuha acorda em um quarto que não é seu e de repente se vê vivendo a vida dos sonhos em Tóquio - mas no corpo de Taki! Em outros lugares, Taki se encontra vivendo a vida de Mitsuha no campo humilde.\r\n\r\nEm busca de uma resposta para esse estranho fenômeno, eles começam a procurar um pelo outro. Kimi no Na wa. gira em torno das ações de Mitsuha e Taki, que começam a ter um impacto dramático na vida um do outro, tecendo-os em um tecido unido pelo destino e pelas circunstâncias.\r\n', 5, '2016-08-26', 1, 'TV', 'Drama, Sobrenatural', 'CoMix Wave Films', 'Makoto Shinkai', 'yourname'),
(51, 'XL Joushi.', 'Com a esperança de ganhar um pouco de dinheiro extra, o funcionário de escritório Saki Watase se inscreve em um programa de revisão de produtos. Mas quando o primeiro produto que seu novo emprego de meio período lhe envia é uma enorme caixa de preservativos XL, Saki decide deixar a tarefa de lado. Mais tarde, enquanto em uma festa com seus colegas de trabalho - incluindo seu competente, mas irritante \"chefe demônio\" Keisuke Sudou - Saki acaba bêbado, então Keisuke se oferece para acompanhá-la para casa.\r\n\r\nApós sua chegada ao apartamento de Saki, no entanto, Keisuke imediatamente percebe a quantidade substancial de preservativos XL de seu subordinado. Quando ela explica as circunstâncias de seu trabalho de meio período, Keisuke se oferece para ajudar nos testes - revelando-se como tamanho XL!', 1, '2019-10-07', 8, 'TV', 'Romance, Hentai', 'Magic Bus', 'Mitsutaka Noshitani', 'xljoushi.');

--
-- Índices para tabelas despejadas
--

--
-- Índices para tabela `pagina`
--
ALTER TABLE `pagina`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de tabelas despejadas
--

--
-- AUTO_INCREMENT de tabela `pagina`
--
ALTER TABLE `pagina`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=59;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
